
package clavealeatoria;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.Random;
import javax.swing.JLabel;

/**
 *
 * @author Hebrondev
 */
public class InterfazClaveAleatoria extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMayorista
     */
    public InterfazClaveAleatoria() {
        initComponents();
    }

    public void copiar(String copiar) {
        StringSelection ss = new StringSelection(copiar);
        //preparo el portapapeles
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        //ajusto el contenido para el portapapeles
        cb.setContents(ss, null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btbGenerar = new javax.swing.JButton();
        lblClave = new javax.swing.JLabel();
        btnCopiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 300));
        setPreferredSize(new java.awt.Dimension(350, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("GENERACION DE CLAVE ALEATORIA");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btbGenerar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btbGenerar.setText("GENERAR");
        btbGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btbGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        lblClave.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblClave.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblClavePropertyChange(evt);
            }
        });
        getContentPane().add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 270, 30));

        btnCopiar.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        btnCopiar.setText("COPIAR");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCopiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 90, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGenerarActionPerformed
        //int clave = txtClave.setText(t);
        
        //generador de numeros aleatorios
        Random numeroAleatorio = new Random();
       
        /*Genera un numero entre 31234567 y 39899999 y lo guarda en la variable claveAleatoria
        (8 Digitos)
        */
        int claveAleatoria = 31234567+numeroAleatorio.nextInt( (39899999+1) - 31234567 );
        
        lblClave.setText(String.valueOf(claveAleatoria));
    }//GEN-LAST:event_btbGenerarActionPerformed

    private void lblClavePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblClavePropertyChange
        lblClave.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_lblClavePropertyChange

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed

        //pasamos como parametro el texto a copiar
        copiar(lblClave.getText());
    }//GEN-LAST:event_btnCopiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazClaveAleatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazClaveAleatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazClaveAleatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazClaveAleatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazClaveAleatoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbGenerar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
